(let ((lisp-dir (expand-file-name "config" user-emacs-directory)))
  (add-to-list 'load-path lisp-dir)
  (let ((default-directory lisp-dir))
    (normal-top-level-add-subdirs-to-load-path)))

(require 'config-essential)
(require 'config-ui)
(require 'config-keybinds)
(require 'config-ide)
(require 'config-completion)
(require 'config-org)
(require 'config-misc)
