* Legion Y540
** Model: Y540-15irh
** Docs: [[https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/legion-series/legion-y540-15irh/documentation/doc_userguide][lenovo.com]]
** BIOS keys:
- Enter BIOS settings: F2
- Boot menu: F12

* Using the nix repl:
#+begin_src bash
nix repl
:l <nixpkgs>
:? # get help
:e lib.mkEnableOption # see source
:q # quit
#+end_src

* Nix flakes
A new project can be created using one of the available templates (completion with tab). Example with rust:
#+begin_src bash
mkdir new-project
cd new-project
nix flake init --template templates#rust
cargo init .
git add -A && git commit -m "Initial commit"
nvim flake.nix # Add rust-analyzer and start coding
#+end_src

I have also created a few of my own templates, located at [[https://github.com/LilleAila/flake-templates]]

* SSH
Generate a new key:
#+begin_src bash
ssh-keygen -t ed25519 -C "your_email@example.com note"
#+end_src

SSH-ing into a server can often result in errors because kitty terminfo files are unavailable. To fix this, run =kitten ssh= instead of =ssh=.

* SOPS
This config needs =SOPS= to work! If it is not configured properly, the user will not have a password!
#+begin_src bash
# Generate age key:
nix shell nixpkgs#age -c age-keygen -o ~/.config/sops/age/keys.txt # Random
## From SSH key: (I used the SSH key from `m1pro14`)
nix run nixpkgs#ssh-to-age -- -private-key -i ~/.ssh/id_ed25519 > ~/.config/sops/age/keys.txt

# Get the public key:
nix shell nixpkgs#age -c age-keygen -y ~/.config/sops/age/keys.txt
#+end_src

The private key file should be at =~/.config/sops/age/keys.txt=.

* Creating writable files
Some programe may need a writable file for some reasom. This is probably one of the worst ways of doing it with a lot of downsides:
** Writable only
Changes to the file are ignored when rebuilding
#+begin_src nix
home.file."test_hm.txt" = {
 text = ''
    abd
    def
    ghi
    jkl
    1234567890
  '';
  onChange = ''
    rm -f $HOME/test.txt
    cp $HOME/test_hm.txt $HOME/test.txt
    chmod u+w $HOME/test.txt
  '';
};
#+end_src

** Symlinked file
When edited, changes are reflected in the source flake.
#+begin_src bash
home.activation.symlinkCustomFiles = lib.hm.dag.entryAfter ["writeBoundary"] ''
  run rm -f $HOME/testFile.txt && ln -s $HOME/dotfiles/home/testFile.txt $HOME/testFile.txt
'';
#+end_src
(pls don't actually use this)

* TODO Configure devenv to use instead of manual devshells
[[https://github.com/cachix/devenv][Devenv]]

* Virtual Machines
** Basic setup steps
- Enable virtualisation stuff in nixOS
- Use =lspci -nnk= to find ids of hardware to pass through
- Make the virtual machine
  - Configure the VM before installation (CPU to =host-passthrough= and use =EFI=)
  - Follow the steps described in the [[https://looking-glass.io/docs/B6/install/][looking glass install guide]].
    - First, install the host and other tools in windows with the default VM config
    - Set video type to =none= and pass through the GPU, a mouse and a keyboard with "add hardware"
    - After booting the VM, plug in a second monitor to install the GPU drivers (it might be possible to do this before removing video drivers, so that an external monitor is not needed)
    - Follow the remaining configuration steps from looking glass. Remember to keep spice enabled, but with video type as =none=!
    - Set up a [[https://github.com/itsmikethetech/Virtual-Display-Driver][virtual display]] so that it works without a monitor plugged in (also possible to do earlier)
  - Use the [[https://christitus.com/windows-tool/][ctt windows utility]] to install other stuff
    - Open administrator command prompt
    - =iwr -useb https://christitus.com/win | iex=
